### ISSUE TITLE
Flutter build web --release minification causes an invalid type comparsion 

### ISSUE THREAD

**Issue by alhamed1** [EPNW/web_ffi#2]
I did some debugging and I found out that the type comparison is the problem in `types.dart`

```dart
int sizeOf<T extends NativeType>() {
  if (_isPointerType<T>()) { 
    size = sizeMap[IntPtr];
  } else {
    size = sizeMap[T];
  }
  print('size: $size');
  if (size != null) {
    return size;
  } else {
    throw new ArgumentError('The type $T is not known!');
  }
}

bool _isPointerType<T extends NativeType>() => // needs to address the changes that resulted from minification
    T.toString().startsWith('Pointer<');

bool _isNativeFunctionType<T extends NativeType>() => // here also
    T.toString().startsWith('NativeFunction<');

bool _isVoidType<T extends NativeType>() => T.toString() == 'Void'; // here also
```
Since minification changes classes variables and functions names, comparing types with `.ToString()` becomes invalid.

**Comment by EPNW** [comment]
Note: This issue was moved from EPNW/opus_flutter#13.

I also started debuging a bit yesterday (I can post my findings tomorrow, as soon as I have access to my debuging machine).

But yes, you seem correct, problem is that web_ffi strongly depends on type names, and minifing breaks that.

I opend flutter/flutter#85835 for that.

**Comment by EP-u-NW** [comment]
As promised above here are my original thoughts about the issue, but I think you have most things already figured out yourself by now:

I think the problem here might be that the `web_ffi` algorithms that handle typisation depend on the type names.

The exception you mention most likly comes from there:
https://github.com/EPNW/web_ffi/blob/60641e6ceac7a0f3057ff468405bb55e8078ddf3/lib/src/ffi/types.dart#L20-L36

When looking at your stack trace, the type `minified:aq1<() => minified:W<minified:cK>>` seems to be missing. Strangely, this type is a generic type: `minified:aq1` is the type, `() => minified:W<minified:cK>` is the type argument. Since the type argument starts with `() =>` we know that the type argument must be a function.

Now, `sizeOf` can be either called directly, or by the framework if:
* something should be allocated or 
* when using the `Pointer.cast` function

I guess the later is the case here, since `Pointer.cast` is frequently called during library initalization.

Since the type we identified above is a generic type, and the type argument is a function I would guess that we are dealing with a `Pointer<NativeFunction>>` here, on which `cast` is called.
Now the thing is that `NativeFunction` is an `@unsized` type, in both `dart:ffi` and `web_ffi`, so `sizeOf` should never be called on it. `web_ffi` checks this by looking at the type name when `Pointer.cast` is used:
https://github.com/EPNW/web_ffi/blob/60641e6ceac7a0f3057ff468405bb55e8078ddf3/lib/src/ffi/types.dart#L41-L42

But if the type name is changed due to minification, `sizeOf` will be called and your error arises.

To be honest, `web_ffi` was only tested with debug builds, we missed testing it with release builds. ~~Type renaming is a big problem, since we use type names in many other places. Even if we could somehow fix the error you get on library initalization, errors at other places are likly to appear.~~

~~For now, the only solution is to disable minification. This could be done using the workaround posted in flutter/flutter#85835.~~

~~For the future we should try to avoid depending on type names so much,  I already have something in mind to fix that, but it will take some days or up to a week until it is release-ready I guess...~~

Edit: See next comment

**Comment by EP-u-NW** [comment]
I had a bit sparetime so I was able to look into it just now, and I think I got it fixed. It is already available on pub as `web_ffi 0.7.2` and also in `opus_flutter 3.0.1`. Can you do some testing if this fixes your problem?

In a few places I was able to remove the dependency on type names, but they are sill needed in some places. For those I came up with the following: Instead of hardcoding the type names into the source code, we extract them at runtime so we know the minifyed name:
https://github.com/EPNW/web_ffi/blob/bf4aad5ac2709dc73a0564f40d1a77612968d8a8/lib/src/internal/type_utils.dart#L52-L55

**Comment by alhamed1** [comment]
Thank you for the effort, the new update works. I've made some workaround to make it work in a release build, and it worked, but you've already solved it, anyhow here is what I did:
In `marshaller.dart`:
```dart
String _pointer = '$Pointer'.substring(0, '$Pointer'.indexOf('<'));

void registerNativeMarshallerType<T extends NativeType>() {
  String t = _typeString<T>();
  _knownTypes['$_pointer<$t>'] = new InvokeHelper<Pointer<T>>(null, null);
  _knownTypes['$_pointer<$_pointer<$t>>'] =
      new InvokeHelper<Pointer<Pointer<T>>>(null, null);
}

void registerNativeMarshallerOpaque<T extends Opaque>() {
  String t = _typeString<T>();
  _knownTypes['$_pointer<$t>'] = new OpaqueInvokeHelper<T>(null, null);
  _knownTypes['$_pointer<$_pointer<$t>>'] =
      new OpaqueInvokeHelperSquare<T>(null, null);
}
```
in `types.dart`:
```dart
String _pointerType = '$NativeFunction'.substring(
    0, '$NativeFunction'.indexOf('<'));

bool _isPointerType<T extends NativeType>() {
  return T.toString().startsWith(_pointerType);
}

bool _isNativeFunctionType<T extends NativeType>() {
  return T.toString().startsWith(_pointerType);
```

**Comment by EP-u-NW** [comment]
Great 👍 
Its kind of funny how you found the exact same solution to the problem 😄 Next time you find an issue and have also the solution, feel free to open a PR 😄
